language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
env:
  matrix:
  - CI=true
  global:
    secure: YanwXDSYuWOGqdwtEFpbHp/SZ9IIt5zYhtwiejPeZedVC8rxjKi6Vp6F+2dsksbDI13YITS/CJV+sDlInKdIOjGzA1x04NfZ8e5nGCjnTkTu+48pAomof4rT820TFftIcli9E2qGWR406ZVvfM9EcL3d1YhfeEI7zWW3LLWUidngxLmYYmOl6rOS6927wpW5IXxXKtUiBKyyI5SuR6iyrIHz1sAHGMNrRary56rDxpWFIxH1Lsk1Cz5vukjhZoHKHVOrbwQnP4guvEXmMQvYAvp3siSXn/vaIskpm5RvkWVTkvsHk8zElhP07TrxmCuX5edT3zA9VqUavXIauP26ElZwobqvZcJ1K1I3lhQKV2tEe1IRnGzUwu4JRvo5M2XtOYkLKwm3U4WV8b3B+sdbwZNn+FYmAVbDMr6K+k31cqs5as+7dJy2mktwXnD4ST4UADairWotq+5eqTsA73DVID09V7dxt1qENWusaq/oDoiHWWMTNHl5WNUbLyfkVKXHcMAzzGu9PcxEaq2gNL2naqRbU6h+YJHknmT6YOWexdgAdvwraVKioBiZ1kfN7ssgrtLgWxXxFwISnSY7zAiMtJ2n2Qs/7LLwOTZDYPntRK6KAhZ4vZJt5xjawr15fLurJUSyP83RjfcvLSgK/I8qab3CaVs3XSxXbGmS5UDDv9A=
before_deploy:
- npm install netlify-cli -g
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: APIKEY
  app: quote-catcher
  on:
    repo: meron93/quote-catcher-client
