language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
env:
- CI=true
before_deploy:
- npm install netlify-cli -g
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: f10e1e4c-a977-48b9-8264-6aaeb7f28fba
  app: quote-catcher
  on:
    repo: meron93/quote-catcher-client
